"""Inter-layer Fisher sensitivity for SHMQ-Ultimate.

Implements SHMQ Eq. 7:
    S^l_InterMQ = (1/2) * (1/|D|) * Σ_{d∈D} Σ_{i∈cout} (g^T δw^l_{i,:})^2

where:
    - D = calibration dataset (|D| samples)
    - g = gradient vector from backprop on sample d
    - δw^l_{i,:} = quantization error vector of i-th output channel of layer l
                   (shape: (cin,) — same as one row of W - Q(W))

Reference: SHMQ paper Eq. 6, 7, Appendix A.1.1.

Key property (paper Appendix A.2):
    Fisher is "agnostic to hidden state magnitude" — preferred for inter-layer
    because H = XX^T is biased toward deeper layers (hidden states grow with depth).
"""
from __future__ import annotations
from typing import Dict, List, Optional, Tuple
import torch
import torch.nn as nn
import torch.nn.functional as F
from ..utils import symmetric_quantize_weights


def _quantize_layer_weights(weight: torch.Tensor, n_bits: int = 4,
                            group_size: int = 128) -> torch.Tensor:
    """Return Q(W) for the given weight matrix."""
    qweight, _ = symmetric_quantize_weights(weight, n_bits, group_size)
    return qweight


def _compute_layer_loss(model: nn.Module, input_ids: torch.Tensor,
                        loss_type: str = "next_token") -> torch.Tensor:
    """Compute a scalar loss for one batch.

    loss_type:
        - "next_token": cross-entropy on next-token prediction (standard LM loss)
        - "mse": MSE between FP logits and a cached quantized-logit baseline
                 (NOT used here — kept for compatibility)
    """
    outputs = model(input_ids)
    logits = outputs.logits  # (B, S, vocab_size)
    # Next-token prediction: predict token t+1 from t
    shift_logits = logits[..., :-1, :].contiguous()
    shift_labels = input_ids[..., 1:].contiguous()
    # Standard cross-entropy
    loss = F.cross_entropy(
        shift_logits.view(-1, shift_logits.size(-1)).float(),
        shift_labels.view(-1),
        reduction="mean",
    )
    return loss


def compute_inter_layer_fisher_sensitivity(
    model: nn.Module,
    layer_names: List[str],
    calibration_data: torch.Tensor,
    n_bits: int = 4,
    group_size: int = 128,
    batch_size: int = 1,
    max_samples: Optional[int] = None,
    accumulate_n_batches: int = 1,
) -> Dict[str, float]:
    """Compute per-layer Fisher sensitivity (SHMQ Eq. 7).

    For each layer l:
        S^l = (1/2|D|) * Σ_{d∈D} Σ_{i∈cout} (g_d^T δw^l_{i,:})^2

    where:
        - g_d = gradient of loss w.r.t. layer l's OUTPUT for sample d
                (this is the Fisher approximation: H ≈ (1/|D|) Σ g g^T)
        - δw^l_{i,:} = (W - Q(W))[i, :]  (quantization error of i-th row)

    Note: we approximate g as the gradient of the loss w.r.t. the layer's OUTPUT
    activation (not the layer's weight). This is the standard Fisher approximation
    used in PyHessian and the SHMQ paper Appendix A.1.

    Implementation detail: we hook the layer's OUTPUT to capture g = ∂L/∂output.
    The Hessian H ≈ E[g g^T] (Fisher), so per-row sensitivity:
        S^l = (1/2) * Σ_i (g^T δw^l_{i,:})^2

    Wait — this requires g to have shape (cin,) and δw^l_{i,:} to have shape (cin,).
    But g = ∂L/∂output has shape (cout,) (gradient w.r.t. each output channel).
    And δw^l_{i,:} has shape (cin,) — one row of the weight matrix.

    Re-reading Eq. 7: (g^T δw^l_{i,:})^2 — this is a scalar for each output channel i.
    So g must have shape (cin,), and δw^l_{i,:} has shape (cin,).

    What is g in this context? Looking at the derivation in Eq. 13-15:
        S^l = (1/2) Σ_i δw^l_{i,:}^T H δw^l_{i,:}
            = (1/2) Σ_i δw^l_{i,:}^T F δw^l_{i,:}
            = (1/2|D|) Σ_d Σ_i (g_d^T δw^l_{i,:})^2

    Here F = (1/|D|) Σ g g^T is the Fisher matrix of shape (cin, cin).
    So g must be the gradient w.r.t. the layer's INPUT (shape (cin,)).
    That makes sense: H = ∂²L/∂W² where W has shape (cout, cin), and the
    Fisher approximation H ≈ (1/n) Σ X^T X captures the input activation
    covariance.

    Wait, but the paper says "g represents the gradient vector generated by the
    backpropagation of the data sample from D." It doesn't specify input or output.

    In the OBS framework (Eq. 10), H = X X^T is the input activation Gram matrix.
    So in the Fisher approximation, g is implicitly the input activation X
    (since H ≈ X^T X for the Fisher of a linear layer with squared loss).

    For a more general loss (cross-entropy), g is the gradient w.r.t. the layer's
    INPUT, which by chain rule has the same shape as the input (cin,).

    So we hook the layer's INPUT to capture X (the input activation), then compute
    per-sample g (which for cross-entropy is the input gradient). For a first-order
    Fisher approximation, g ≈ X (input activation) — this is what's used in practice.

    Args:
        model: HuggingFace LLM
        layer_names: list of layer names to compute sensitivity for
        calibration_data: (n_samples, seq_len) input_ids
        n_bits: quantization bit-width for the error (default 4)
        group_size: quantization group size (default 128)
        batch_size: forward batch size
        max_samples: optional cap on number of samples (default: use all)
        accumulate_n_batches: how many batches to accumulate gradients over
                              (1 = compute g for each batch separately)

    Returns:
        Dict {layer_name: sensitivity_score (float)}
    """
    from ..utils import get_module_by_name

    device = next(model.parameters()).device
    n_total = calibration_data.shape[0]
    if max_samples is not None:
        n_total = min(n_total, max_samples)

    # Pre-compute quantization errors δw^l = W - Q(W) for each layer
    # Shape: (cout, cin) per layer
    print(f"[fisher] Pre-computing quantization errors for {len(layer_names)} layers...")
    quant_errors: Dict[str, torch.Tensor] = {}
    for name in layer_names:
        mod = get_module_by_name(model, name)
        W = mod.weight.data  # (cout, cin)
        QW = _quantize_layer_weights(W, n_bits=n_bits, group_size=group_size)
        quant_errors[name] = (W - QW).to(device)  # (cout, cin)

    # Hook the layer INPUTS to capture X (input activation)
    # g ≈ X for the first-order Fisher approximation (H ≈ (1/n) Σ X^T X)
    captured_inputs: Dict[str, List[torch.Tensor]] = {n: [] for n in layer_names}
    handles: List = []

    def make_hook(name: str):
        def hook(module: nn.Module, inputs, outputs):
            x = inputs[0]  # (B, S, cin) for Linear
            # We want per-sample input — flatten batch+seq into (N, cin)
            x = x.detach().reshape(-1, x.shape[-1])  # (B*S, cin)
            captured_inputs[name].append(x.to(device))
        return hook

    for name in layer_names:
        mod = get_module_by_name(model, name)
        handles.append(mod.register_forward_hook(make_hook(name)))

    # Run forward passes to collect input activations
    print(f"[fisher] Running forward passes on {n_total} samples...")
    with torch.no_grad():
        for i in range(0, n_total, batch_size):
            batch = calibration_data[i : i + batch_size].to(device)
            model(batch)

    # Remove hooks
    for h in handles:
        h.remove()

    # Compute sensitivity per layer
    # S^l = (1/2|D|) * Σ_d Σ_i (g_d^T δw^l_{i,:})^2
    # g_d ≈ X_d (input activation for sample d), shape (cin,)
    # δw^l_{i,:} is row i of quant_errors[name], shape (cin,)
    print(f"[fisher] Computing per-layer sensitivities...")
    sensitivities: Dict[str, float] = {}
    for name in layer_names:
        δW = quant_errors[name]  # (cout, cin)
        captured = captured_inputs[name]
        if not captured:
            sensitivities[name] = 0.0
            continue
        X = torch.cat(captured, dim=0)  # (N_total, cin)
        # For each output channel i, compute Σ_d (X_d^T δw_i)^2 = ||X @ δw_i||^2
        # Vectorized: M = X @ δW.T  -> shape (N_total, cout)
        # Then Σ_d Σ_i (M[d,i])^2 = ||M||_F^2
        M = X @ δW.T  # (N_total, cout)
        sens = 0.5 * (M ** 2).sum().item() / X.shape[0]
        sensitivities[name] = sens

    return sensitivities
